# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eUU36m_dQC6x5a_-W-nDjbi29-YsXqgF
"""

import streamlit as st
import numpy as np
import pandas as pd
import tensorflow as tf
import joblib

# بارگذاری مدل و اسکیلر
model = tf.keras.models.load_model("laptop_price_model.h5")
scaler = joblib.load("scaler.pkl")

st.set_page_config(page_title="پیش‌بینی قیمت لپ‌تاپ", layout="centered")

st.title("💻 پیش‌بینی قیمت لپ‌تاپ با یادگیری ماشین")
st.write("لطفاً ویژگی‌های لپ‌تاپ مورد نظر را وارد کنید:")

# ورودی‌های کاربر
inches = st.slider("📐 اندازه صفحه (Inches)", 10.0, 20.0, 15.6)
ram = st.slider("🧠 رم (GB)", 2, 64, 8)
weight = st.number_input("⚖️ وزن لپ‌تاپ (کیلوگرم)", 0.5, 5.0, 1.5)
memory = st.number_input("💾 حافظه ذخیره‌سازی (GB)", 128, 5000, 512)
cpu_brand = st.selectbox("🧮 برند پردازنده", ['Intel', 'AMD', 'Samsung', 'Apple'])
gpu_brand = st.selectbox("🎮 برند کارت گرافیک", ['Intel', 'Nvidia', 'AMD'])

# دسته‌بندی به عدد تبدیل می‌شود (سازگار با مدل)
cpu_map = {'Intel': 2, 'AMD': 0, 'Samsung': 3, 'Apple': 1}
gpu_map = {'Intel': 1, 'Nvidia': 2, 'AMD': 0}

cpu_code = cpu_map[cpu_brand]
gpu_code = gpu_map[gpu_brand]

# ویژگی‌های عددی و بردن به مدل
input_data = np.array([[inches, ram, weight, memory, cpu_code, gpu_code]])

# اسکیل کردن
input_scaled = scaler.transform(input_data)

# پیش‌بینی
if st.button("📊 پیش‌بینی قیمت"):
    predicted_price = model.predict(input_scaled)[0][0]
    st.success(f"💰 قیمت پیش‌بینی‌شده: {predicted_price:.2f} (مقدار نرمال‌شده)")
    st.caption("نکته: مقدار نهایی نرمال‌شده است چون برای آموزش از PowerTransformer استفاده شده.")
